// <auto-generated />
using System;
using FinBet_Web_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinBet_Web_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210210171951_RemovingConotation")]
    partial class RemovingConotation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FinBet.Models.Lexicon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Lexicons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "nice",
                            Rating = 0.4m
                        },
                        new
                        {
                            Id = 2,
                            Name = "excellent",
                            Rating = 0.8m
                        },
                        new
                        {
                            Id = 3,
                            Name = "modest",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "horrible",
                            Rating = -0.8m
                        },
                        new
                        {
                            Id = 5,
                            Name = "ugly",
                            Rating = -0.5m
                        });
                });

            modelBuilder.Entity("FinBet_Web_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
